name: Build NuGet Package

on: [workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init

    - name: Build Package
      run: . .\build.ps1; Build-Host -BuildType "Release" -Arch "x64"

    - uses: actions/upload-artifact@v2
      with:
        path: dist
